// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FileProcessor.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("GetFileImportDetails")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("base")]
    [global::NUnit.Framework.CategoryAttribute("shared")]
    [global::NUnit.Framework.CategoryAttribute("getfileimportdetails")]
    [global::NUnit.Framework.CategoryAttribute("fileprofiles")]
    public partial class GetFileImportDetailsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "shared",
                "getfileimportdetails",
                "fileprofiles"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "GetFileImportDetails", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GetFileImportDetails.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
            global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table10.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST  Scope",
                        "A scope for Transaction Processor REST"});
            table10.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST Scope",
                        "A scope for File Processor REST"});
#line 5
 await testRunner.GivenAsync("I create the following api scopes", ((string)(null)), table10, "Given ");
#line hidden
            global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table11.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        "MerchantId, EstateId, role"});
            table11.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST",
                        "Secret1",
                        "fileProcessor",
                        ""});
#line 10
 await testRunner.GivenAsync("the following api resources exist", ((string)(null)), table11, "Given ");
#line hidden
            global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                        "ClientId",
                        "ClientName",
                        "Secret",
                        "Scopes",
                        "GrantTypes"});
            table12.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "transactionProcessor,fileProcessor",
                        "client_credentials"});
#line 15
 await testRunner.GivenAsync("the following clients exist", ((string)(null)), table12, "Given ");
#line hidden
            global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                        "ClientId"});
            table13.AddRow(new string[] {
                        "serviceClient"});
#line 19
 await testRunner.GivenAsync("I have a token to access the estate management and transaction processor resource" +
                    "s", ((string)(null)), table13, "Given ");
#line hidden
            global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                        "Alias",
                        "FileProfileId",
                        "Name",
                        "ListeningDirectory",
                        "RequestType",
                        "OperatorName",
                        "LineTerminator",
                        "FileFormatHandler"});
            table14.AddRow(new string[] {
                        "Safaricom Topup",
                        "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                        "Safaricom Topup",
                        "/home/txnproc/bulkfiles/safaricom",
                        "SafaricomTopupRequest",
                        "Safaricom",
                        "1",
                        "SafaricomFileFormatHandler"});
            table14.AddRow(new string[] {
                        "Voucher Issue",
                        "8806EDBC-3ED6-406B-9E5F-A9078356BE99",
                        "Voucher Issue",
                        "/home/txnproc/bulkfiles/voucher",
                        "VoucherRequest",
                        "Voucher",
                        "1",
                        "VoucherFileFormatHandler"});
#line 23
 await testRunner.WhenAsync("I create the following file profiles", ((string)(null)), table14, "When ");
#line hidden
            global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                        "EstateName"});
            table15.AddRow(new string[] {
                        "Test Estate 1"});
#line 28
 await testRunner.GivenAsync("I have created the following estates", ((string)(null)), table15, "Given ");
#line hidden
            global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table16.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "True",
                        "True"});
            table16.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "True",
                        "True"});
#line 32
 await testRunner.GivenAsync("I have created the following operators", ((string)(null)), table16, "Given ");
#line hidden
            global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName"});
            table17.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom"});
            table17.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher"});
#line 37
 await testRunner.AndAsync("I have assigned the following operators to the estates", ((string)(null)), table17, "And ");
#line hidden
            global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription"});
            table18.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract"});
            table18.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "Hospital 1 Contract"});
#line 42
 await testRunner.GivenAsync("I create a contract with the following values", ((string)(null)), table18, "Given ");
#line hidden
            global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "DisplayText",
                        "Value",
                        "ProductType"});
            table19.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        "",
                        "MobileTopup"});
            table19.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "Hospital 1 Contract",
                        "10 KES",
                        "10 KES",
                        "",
                        "Voucher"});
#line 47
 await testRunner.WhenAsync("I create the following Products", ((string)(null)), table19, "When ");
#line hidden
            global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "CalculationType",
                        "FeeDescription",
                        "Value"});
            table20.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Fixed",
                        "Merchant Commission",
                        "2.50"});
#line 52
 await testRunner.WhenAsync("I add the following Transaction Fees", ((string)(null)), table20, "When ");
#line hidden
            global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                        "MerchantName",
                        "AddressLine1",
                        "Town",
                        "Region",
                        "PostalCode",
                        "Country",
                        "ContactName",
                        "EmailAddress",
                        "EstateName"});
            table21.AddRow(new string[] {
                        "Test Merchant 1",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "TE57 1NG",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant1.co.uk",
                        "Test Estate 1"});
            table21.AddRow(new string[] {
                        "Test Merchant 2",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "TE57 2NG",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant2.co.uk",
                        "Test Estate 1"});
#line 56
 await testRunner.GivenAsync("I create the following merchants", ((string)(null)), table21, "Given ");
#line hidden
            global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                        "OperatorName",
                        "MerchantName",
                        "MerchantNumber",
                        "TerminalNumber",
                        "EstateName"});
            table22.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table22.AddRow(new string[] {
                        "Voucher",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table22.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
            table22.AddRow(new string[] {
                        "Voucher",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
#line 61
 await testRunner.GivenAsync("I have assigned the following  operator to the merchants", ((string)(null)), table22, "Given ");
#line hidden
            global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                        "DeviceIdentifier",
                        "MerchantName",
                        "EstateName"});
            table23.AddRow(new string[] {
                        "123456780",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table23.AddRow(new string[] {
                        "123456781",
                        "Test Merchant 2",
                        "Test Estate 1"});
#line 68
 await testRunner.GivenAsync("I have assigned the following devices to the merchants", ((string)(null)), table23, "Given ");
#line hidden
            global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "MerchantName",
                        "ContractDescription"});
            table24.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "Safaricom Contract"});
            table24.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "Hospital 1 Contract"});
            table24.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 2",
                        "Safaricom Contract"});
            table24.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 2",
                        "Hospital 1 Contract"});
#line 73
 await testRunner.WhenAsync("I add the following contracts to the following merchants", ((string)(null)), table24, "When ");
#line hidden
            global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                        "Reference",
                        "Amount",
                        "DateTime",
                        "MerchantName",
                        "EstateName"});
            table25.AddRow(new string[] {
                        "Deposit1",
                        "300.00",
                        "Today",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table25.AddRow(new string[] {
                        "Deposit1",
                        "300.00",
                        "Today",
                        "Test Merchant 2",
                        "Test Estate 1"});
#line 80
 await testRunner.GivenAsync("I make the following manual merchant deposits", ((string)(null)), table25, "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/GetFileImportDetails.feature.ndjson", 3);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Get File Import Log Details")]
        [global::NUnit.Framework.CategoryAttribute("PRTest")]
        public async global::System.Threading.Tasks.Task GetFileImportLogDetails()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get File Import Log Details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table26.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table26.AddRow(new string[] {
                            "D",
                            "07777777775",
                            "100"});
                table26.AddRow(new string[] {
                            "T",
                            "1",
                            ""});
#line 87
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup1.txt\' with the following contents", ((string)(null)), table26, "Given ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId",
                            "UploadDateTime"});
                table27.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476",
                            "Today"});
#line 92
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table27, "And ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table28.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table28.AddRow(new string[] {
                            "D",
                            "07777777776",
                            "150"});
                table28.AddRow(new string[] {
                            "T",
                            "1",
                            ""});
#line 96
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup2.txt\' with the following contents", ((string)(null)), table28, "Given ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId",
                            "UploadDateTime"});
                table29.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476",
                            "Today"});
#line 101
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table29, "And ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3",
                            "Column4"});
                table30.AddRow(new string[] {
                            "H",
                            "20210508",
                            "",
                            ""});
                table30.AddRow(new string[] {
                            "D",
                            "Hospital 1",
                            "07777777775",
                            "10"});
                table30.AddRow(new string[] {
                            "D",
                            "Hospital 1",
                            "testrecipient1@recipient.com",
                            "10"});
                table30.AddRow(new string[] {
                            "T",
                            "1",
                            "",
                            ""});
#line 105
 await testRunner.GivenAsync("I have a file named \'VoucherIssue1.txt\' with the following contents", ((string)(null)), table30, "Given ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId",
                            "UploadDateTime"});
                table31.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "8806EDBC-3ED6-406B-9E5F-A9078356BE99",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476",
                            "Today"});
#line 111
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table31, "And ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "ImportLogDate",
                            "FileCount"});
                table32.AddRow(new string[] {
                            "Today",
                            "3"});
#line 115
 await testRunner.WhenAsync("I get the \'Test Estate 1\' import logs between \'Yesterday\' and \'Today\' the followi" +
                        "ng data is returned", ((string)(null)), table32, "When ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "MerchantName",
                            "OriginalFileName"});
                table33.AddRow(new string[] {
                            "Test Merchant 1",
                            "SafarcomTopup1.txt"});
                table33.AddRow(new string[] {
                            "Test Merchant 2",
                            "SafarcomTopup2.txt"});
                table33.AddRow(new string[] {
                            "Test Merchant 1",
                            "VoucherIssue1.txt"});
#line 119
 await testRunner.WhenAsync("I get the \'Test Estate 1\' import log for \'Today\' the following file information i" +
                        "s returned", ((string)(null)), table33, "When ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "ProcessingCompleted",
                            "NumberOfLines",
                            "TotaLines",
                            "SuccessfulLines",
                            "IgnoredLines",
                            "FailedLines",
                            "NotProcessedLines"});
                table34.AddRow(new string[] {
                            "True",
                            "3",
                            "3",
                            "1",
                            "2",
                            "0",
                            "0"});
#line 125
 await testRunner.WhenAsync("I get the file \'SafarcomTopup1.txt\' for Estate \'Test Estate 1\' the following file" +
                        " information is returned", ((string)(null)), table34, "When ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "LineNumber",
                            "Data",
                            "Result"});
                table35.AddRow(new string[] {
                            "1",
                            "H,20210508,",
                            "Ignored"});
                table35.AddRow(new string[] {
                            "2",
                            "D,07777777775,100",
                            "Successful"});
                table35.AddRow(new string[] {
                            "3",
                            "T,1,",
                            "Ignored"});
#line 129
 await testRunner.WhenAsync("I get the file \'SafarcomTopup1.txt\' for Estate \'Test Estate 1\' the following file" +
                        " lines are returned", ((string)(null)), table35, "When ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "ProcessingCompleted",
                            "NumberOfLines",
                            "TotaLines",
                            "SuccessfulLines",
                            "IgnoredLines",
                            "FailedLines",
                            "NotProcessedLines"});
                table36.AddRow(new string[] {
                            "True",
                            "3",
                            "3",
                            "1",
                            "2",
                            "0",
                            "0"});
#line 135
 await testRunner.WhenAsync("I get the file \'SafarcomTopup2.txt\' for Estate \'Test Estate 1\' the following file" +
                        " information is returned", ((string)(null)), table36, "When ");
#line hidden
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "LineNumber",
                            "Data",
                            "Result"});
                table37.AddRow(new string[] {
                            "1",
                            "H,20210508,",
                            "Ignored"});
                table37.AddRow(new string[] {
                            "2",
                            "D,07777777776,150",
                            "Successful"});
                table37.AddRow(new string[] {
                            "3",
                            "T,1,",
                            "Ignored"});
#line 139
 await testRunner.WhenAsync("I get the file \'SafarcomTopup2.txt\' for Estate \'Test Estate 1\' the following file" +
                        " lines are returned", ((string)(null)), table37, "When ");
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "ProcessingCompleted",
                            "NumberOfLines",
                            "TotaLines",
                            "SuccessfulLines",
                            "IgnoredLines",
                            "FailedLines",
                            "NotProcessedLines"});
                table38.AddRow(new string[] {
                            "True",
                            "4",
                            "4",
                            "2",
                            "2",
                            "0",
                            "0"});
#line 145
 await testRunner.WhenAsync("I get the file \'VoucherIssue1.txt\' for Estate \'Test Estate 1\' the following file " +
                        "information is returned", ((string)(null)), table38, "When ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "LineNumber",
                            "Data",
                            "Result"});
                table39.AddRow(new string[] {
                            "1",
                            "H,20210508,,",
                            "Ignored"});
                table39.AddRow(new string[] {
                            "2",
                            "D,Hospital 1,07777777775,10",
                            "Successful"});
                table39.AddRow(new string[] {
                            "3",
                            "D,Hospital 1,testrecipient1@recipient.com,10",
                            "Successful"});
                table39.AddRow(new string[] {
                            "4",
                            "T,1,,",
                            "Ignored"});
#line 149
 await testRunner.WhenAsync("I get the file \'VoucherIssue1.txt\' for Estate \'Test Estate 1\' the following file " +
                        "lines are returned", ((string)(null)), table39, "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
