// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FileProcessor.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Process Topup CSV Files")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("base")]
    [global::NUnit.Framework.CategoryAttribute("shared")]
    public partial class ProcessTopupCSVFilesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "shared"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Process Topup CSV Files", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ProcessTopupCSV.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
            global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table40.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST  Scope",
                        "A scope for Transaction Processor REST"});
            table40.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST Scope",
                        "A scope for File Processor REST"});
#line 5
 await testRunner.GivenAsync("I create the following api scopes", ((string)(null)), table40, "Given ");
#line hidden
            global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table41.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        "MerchantId, EstateId, role"});
            table41.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST",
                        "Secret1",
                        "fileProcessor",
                        ""});
#line 10
 await testRunner.GivenAsync("the following api resources exist", ((string)(null)), table41, "Given ");
#line hidden
            global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                        "ClientId",
                        "ClientName",
                        "Secret",
                        "Scopes",
                        "GrantTypes"});
            table42.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "transactionProcessor,fileProcessor",
                        "client_credentials"});
#line 15
 await testRunner.GivenAsync("the following clients exist", ((string)(null)), table42, "Given ");
#line hidden
            global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                        "ClientId"});
            table43.AddRow(new string[] {
                        "serviceClient"});
#line 19
 await testRunner.GivenAsync("I have a token to access the estate management and transaction processor resource" +
                    "s", ((string)(null)), table43, "Given ");
#line hidden
            global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                        "Alias",
                        "FileProfileId",
                        "Name",
                        "ListeningDirectory",
                        "RequestType",
                        "OperatorName",
                        "LineTerminator",
                        "FileFormatHandler"});
            table44.AddRow(new string[] {
                        "Safaricom Topup",
                        "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                        "Safaricom Topup",
                        "/home/txnproc/bulkfiles/safaricom",
                        "SafaricomTopupRequest",
                        "Safaricom",
                        "\n",
                        "SafaricomFileFormatHandler"});
            table44.AddRow(new string[] {
                        "Voucher Issue",
                        "8806EDBC-3ED6-406B-9E5F-A9078356BE99",
                        "Voucher Issue",
                        "/home/txnproc/bulkfiles/voucher",
                        "VoucherRequest",
                        "Voucher",
                        "\n",
                        "VoucherFileFormatHandler"});
#line 23
 await testRunner.WhenAsync("I create the following file profiles", ((string)(null)), table44, "When ");
#line hidden
            global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                        "EstateName"});
            table45.AddRow(new string[] {
                        "Test Estate 1"});
#line 28
 await testRunner.GivenAsync("I have created the following estates", ((string)(null)), table45, "Given ");
#line hidden
            global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table46.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "True",
                        "True"});
            table46.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "True",
                        "True"});
#line 32
 await testRunner.GivenAsync("I have created the following operators", ((string)(null)), table46, "Given ");
#line hidden
            global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName"});
            table47.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom"});
            table47.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher"});
#line 37
 await testRunner.AndAsync("I have assigned the following operators to the estates", ((string)(null)), table47, "And ");
#line hidden
            global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription"});
            table48.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract"});
            table48.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "Hospital 1 Contract"});
#line 42
 await testRunner.GivenAsync("I create a contract with the following values", ((string)(null)), table48, "Given ");
#line hidden
            global::Reqnroll.Table table49 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "DisplayText",
                        "Value",
                        "ProductType"});
            table49.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        "",
                        "MobileTopup"});
            table49.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "Hospital 1 Contract",
                        "10 KES",
                        "10 KES",
                        "",
                        "Voucher"});
#line 47
 await testRunner.WhenAsync("I create the following Products", ((string)(null)), table49, "When ");
#line hidden
            global::Reqnroll.Table table50 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "CalculationType",
                        "FeeDescription",
                        "Value"});
            table50.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Fixed",
                        "Merchant Commission",
                        "2.50"});
#line 52
 await testRunner.WhenAsync("I add the following Transaction Fees", ((string)(null)), table50, "When ");
#line hidden
            global::Reqnroll.Table table51 = new global::Reqnroll.Table(new string[] {
                        "MerchantName",
                        "AddressLine1",
                        "Town",
                        "Region",
                        "PostalCode",
                        "Country",
                        "ContactName",
                        "EmailAddress",
                        "EstateName"});
            table51.AddRow(new string[] {
                        "Test Merchant 1",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "TE57 1NG",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant1.co.uk",
                        "Test Estate 1"});
#line 56
 await testRunner.GivenAsync("I create the following merchants", ((string)(null)), table51, "Given ");
#line hidden
            global::Reqnroll.Table table52 = new global::Reqnroll.Table(new string[] {
                        "OperatorName",
                        "MerchantName",
                        "MerchantNumber",
                        "TerminalNumber",
                        "EstateName"});
            table52.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table52.AddRow(new string[] {
                        "Voucher",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
#line 60
 await testRunner.GivenAsync("I have assigned the following  operator to the merchants", ((string)(null)), table52, "Given ");
#line hidden
            global::Reqnroll.Table table53 = new global::Reqnroll.Table(new string[] {
                        "DeviceIdentifier",
                        "MerchantName",
                        "EstateName"});
            table53.AddRow(new string[] {
                        "123456780",
                        "Test Merchant 1",
                        "Test Estate 1"});
#line 65
 await testRunner.GivenAsync("I have assigned the following devices to the merchants", ((string)(null)), table53, "Given ");
#line hidden
            global::Reqnroll.Table table54 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "MerchantName",
                        "ContractDescription"});
            table54.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "Safaricom Contract"});
            table54.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "Hospital 1 Contract"});
#line 69
 await testRunner.WhenAsync("I add the following contracts to the following merchants", ((string)(null)), table54, "When ");
#line hidden
            global::Reqnroll.Table table55 = new global::Reqnroll.Table(new string[] {
                        "Reference",
                        "Amount",
                        "DateTime",
                        "MerchantName",
                        "EstateName"});
            table55.AddRow(new string[] {
                        "Deposit1",
                        "300.00",
                        "Today",
                        "Test Merchant 1",
                        "Test Estate 1"});
#line 74
 await testRunner.GivenAsync("I make the following manual merchant deposits", ((string)(null)), table55, "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ProcessTopupCSV.feature.ndjson", 7);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Process Safaricom Topup File with 1 detail row")]
        [global::NUnit.Framework.CategoryAttribute("Nightly")]
        public async global::System.Threading.Tasks.Task ProcessSafaricomTopupFileWith1DetailRow()
        {
            string[] tagsOfScenario = new string[] {
                    "Nightly"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process Safaricom Topup File with 1 detail row", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 79
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table56 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table56.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table56.AddRow(new string[] {
                            "D",
                            "07777777775",
                            "100"});
                table56.AddRow(new string[] {
                            "T",
                            "1",
                            ""});
#line 80
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup.txt\' with the following contents", ((string)(null)), table56, "Given ");
#line hidden
                global::Reqnroll.Table table57 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId"});
                table57.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476"});
#line 85
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table57, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Process Safaricom Topup File with 2 detail rows")]
        [global::NUnit.Framework.CategoryAttribute("Nightly")]
        public async global::System.Threading.Tasks.Task ProcessSafaricomTopupFileWith2DetailRows()
        {
            string[] tagsOfScenario = new string[] {
                    "Nightly"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process Safaricom Topup File with 2 detail rows", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table58 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table58.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table58.AddRow(new string[] {
                            "D",
                            "07777777775",
                            "100"});
                table58.AddRow(new string[] {
                            "D",
                            "07777777776",
                            "200"});
                table58.AddRow(new string[] {
                            "T",
                            "2",
                            ""});
#line 93
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup.txt\' with the following contents", ((string)(null)), table58, "Given ");
#line hidden
                global::Reqnroll.Table table59 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId"});
                table59.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476"});
#line 99
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table59, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Process 2 Safaricom Topup Files")]
        [global::NUnit.Framework.CategoryAttribute("Nightly")]
        public async global::System.Threading.Tasks.Task Process2SafaricomTopupFiles()
        {
            string[] tagsOfScenario = new string[] {
                    "Nightly"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process 2 Safaricom Topup Files", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 106
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table60 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table60.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table60.AddRow(new string[] {
                            "D",
                            "07777777775",
                            "100"});
                table60.AddRow(new string[] {
                            "T",
                            "1",
                            ""});
#line 107
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup1.txt\' with the following contents", ((string)(null)), table60, "Given ");
#line hidden
                global::Reqnroll.Table table61 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId"});
                table61.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476"});
#line 112
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table61, "And ");
#line hidden
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table62.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table62.AddRow(new string[] {
                            "D",
                            "07777777776",
                            "150"});
                table62.AddRow(new string[] {
                            "D",
                            "07777777777",
                            "50"});
                table62.AddRow(new string[] {
                            "T",
                            "2",
                            ""});
#line 116
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup2.txt\' with the following contents", ((string)(null)), table62, "Given ");
#line hidden
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476"});
#line 122
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table63, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Process Duplicate Safaricom Topup File with 1 detail row")]
        [global::NUnit.Framework.CategoryAttribute("PRTest")]
        [global::NUnit.Framework.CategoryAttribute("Nightly")]
        public async global::System.Threading.Tasks.Task ProcessDuplicateSafaricomTopupFileWith1DetailRow()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest",
                    "Nightly"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process Duplicate Safaricom Topup File with 1 detail row", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 130
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table64 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table64.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table64.AddRow(new string[] {
                            "D",
                            "07777777775",
                            "100"});
                table64.AddRow(new string[] {
                            "D",
                            "07777777776",
                            "200"});
                table64.AddRow(new string[] {
                            "T",
                            "1",
                            ""});
#line 131
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup1.txt\' with the following contents", ((string)(null)), table64, "Given ");
#line hidden
                global::Reqnroll.Table table65 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId"});
                table65.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476"});
#line 137
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table65, "And ");
#line hidden
                global::Reqnroll.Table table66 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table66.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table66.AddRow(new string[] {
                            "D",
                            "07777777775",
                            "100"});
                table66.AddRow(new string[] {
                            "D",
                            "07777777776",
                            "200"});
                table66.AddRow(new string[] {
                            "T",
                            "1",
                            ""});
#line 143
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup2.txt\' with the following contents", ((string)(null)), table66, "Given ");
#line hidden
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId"});
                table67.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476"});
#line 149
 await testRunner.AndAsync("I upload this file for processing an error should be returned indicating the file" +
                        " is a duplicate", ((string)(null)), table67, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Process Safaricom Topup File with Upload Date Time")]
        [global::NUnit.Framework.CategoryAttribute("Nightly")]
        public async global::System.Threading.Tasks.Task ProcessSafaricomTopupFileWithUploadDateTime()
        {
            string[] tagsOfScenario = new string[] {
                    "Nightly"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process Safaricom Topup File with Upload Date Time", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 155
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table68 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table68.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table68.AddRow(new string[] {
                            "D",
                            "07777777775",
                            "100"});
                table68.AddRow(new string[] {
                            "T",
                            "1",
                            ""});
#line 156
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup.txt\' with the following contents", ((string)(null)), table68, "Given ");
#line hidden
                global::Reqnroll.Table table69 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId",
                            "UploadDateTime"});
                table69.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476",
                            "Today"});
#line 161
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table69, "And ");
#line hidden
#line 165
 await testRunner.WhenAsync("I get the import log for estate \'Test Estate 1\' the date on the import log is \'To" +
                        "day\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table70 = new global::Reqnroll.Table(new string[] {
                            "Column1",
                            "Column2",
                            "Column3"});
                table70.AddRow(new string[] {
                            "H",
                            "20210508",
                            ""});
                table70.AddRow(new string[] {
                            "D",
                            "07777777775",
                            "200"});
                table70.AddRow(new string[] {
                            "T",
                            "1",
                            ""});
#line 167
 await testRunner.GivenAsync("I have a file named \'SafarcomTopup1.txt\' with the following contents", ((string)(null)), table70, "Given ");
#line hidden
                global::Reqnroll.Table table71 = new global::Reqnroll.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "FileProfileId",
                            "UserId",
                            "UploadDateTime"});
                table71.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "B2A59ABF-293D-4A6B-B81B-7007503C3476",
                            "ABA59ABF-293D-4A6B-B81B-7007503C3476",
                            "01/09/2021"});
#line 172
 await testRunner.AndAsync("I upload this file for processing", ((string)(null)), table71, "And ");
#line hidden
#line 176
 await testRunner.WhenAsync("I get the import log for estate \'Test Estate 1\' the date on the import log is \'01" +
                        "/09/2021\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
